services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"

  service1:
    build: ./service1
    ports:
      - "5001:5001"

  servicevictoria:
    build: ./servicevictoria
    ports:
      - "5003:5003"

  servicesalome:
    build: ./servicesalome
    ports:
      - "5005:5005"


  serviceemily:
    build: ./serviceemily
    ports:
      - "5002:5002"
      
  serviceangie:
    build: ./serviceangie
    ports:
      - "5006:5006"
 
  serviceandres:
    build: ./serviceandres
    ports:
      - "5007:5007"
      
 


